### ISSUE TITLE
util is not a core package

### ISSUE THREAD

**Issue by robintindale** [skpm/console#1]
When I access `console` using `const console = require('@skpm/console')` and try and use it, it prints `util is not a core package`

I just cloned the default `skpm` template and added `devDependency` of `"@skpm/console": "^0.1.3",`. Is `skpm` supposed to be clever about `@skpm` modules?

**Comment by mathieudutour** [comment]
This package is shipped with Sketch 50 so you don’t need to require it. If you want to polyfill console for older Sketch version, use `Sketch-polyfill-console`

**Comment by mathieudutour** [comment]
(The `util` package is also shipped with Sketch 50)

**Comment by robintindale** [comment]
oh OK I see :) Seems like I've got burned a few times for not being on Sketch 50 recently (mostly the `console`) - I think it would be nice to leave notes or comments so people still developing on production don't get left behind / confused

**Comment by mathieudutour** [comment]
yeah I'll write a post on the forum to explain the changes
