### ISSUE TITLE
Console.error doesn’t provide a stack trace

### ISSUE THREAD

**Issue by KevinGutowski** [skpm/console#3]
```
let fuel = 99

function launch_rocket() {
  function warning_msg() {
    console.error("Not enough fuel.")
  }
  if (fuel >=100) {
  } else {
    warning_msg()
  }
}

launch_rocket()
```

This just logs the msg "Not enough fuel and not
```
Not enough fuel.
warning_msg   @ script:9
launch_rocket @ script:14
(anonymous)   @ script: 17
```

**Comment by KevinGutowski** [comment]
Also not sure where I should put this issue (on the Sketch API or here?)

**Comment by mathieudutour** [comment]
console.error isn't supposed to show a stack trace, it just outputs to stderr.

You can try for yourself in the node REPL: `node` -> `console.error('test')`

It shows a stack trace in the browser but that's browser specific
