### ISSUE TITLE
Logging a NSRange struct doesn’t return anything helpful

### ISSUE THREAD

**Issue by KevinGutowski** [skpm/console#4]
```
let myRange = NSMakeRange(0,5)
console.log(myRange)
//Struct NSRange has no member named Symbol.toStringTag
```

It would be nice if there was something a bit better logged to the console. Right now I just do `console.log(myRange.length)` and `console.log(myRange.location)` to get anything useful.

**Comment by mathieudutour** [comment]
fixed in https://github.com/skpm/console/commit/91791a321fe1643de09884c3ba8d75a44312eddf
